# based on the template from
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

variables:
  MAVEN_CLI_OPTS: "--batch-mode --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.6-jdk-11

cache:
  paths:
    - .m2

# For merge requests do not `deploy` but only run `verify`.
.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - main

# Verify merge requests
verify:jdk11:
  <<: *verify


pages:
  stage: deploy
  script:
    - mkdir -p public
    - mvn clean
    - mkdir -p target
    - mvn test -l target/mvn.log || mvn compile
    - cp target/index.html public/
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


deploy:jdk11:
  stage: deploy
  script:
    - if [ ! -f resources/ci_settings.xml ];
        then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions.";
      fi
    - 'mvn $MAVEN_CLI_OPTS deploy -s resources/ci_settings.xml'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
