name: Update github pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: assert that we have public directory
        run: mkdir -p public

      - name: mvn clean
        run: mvn clean

      - name: assert that we have target directory
        run: mkdir -p target

      - name: run tests and generate report
        run: mvn test -l target/mvn.log || mvn compile

      - name: copy report to pages
        run: cp target/index.html public/

      - name: Deploy descriptor file on Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
